#!/bin/sh

# find mounted persistence partition
eval "$(awk '$2 ~ "^/run/live/persistence/" { print "data_partition_device="$1"; mount_point="$2"; filesystem="$3"; mount_options="$4"" }' /proc/mounts)"

if [ -z "$data_partition_device" ]
then
	echo "no mounted persistence partition found, exiting."
	exit 0
fi

# shellcheck disable=SC2154
if echo "$mount_options" | tr ',' '\n' | grep -q "^ro$"
then
	echo "persistence $MOUNT_POINT is read-only, exiting"
	exit 0
fi

# make sure that unprivileged users have access to file system root
# otherwise they are unable to access btrfs snapshots
# shellcheck disable=SC2154
echo "changing permissions of \"$mount_point\" to 755"
chmod 755 "$mount_point"

# mount snapshots subvolume of btrfs persistence
# shellcheck disable=SC2154
echo "filesystem: \"$filesystem\""
if [ "$filesystem" = "btrfs" ]
then
	# activate compression via remount
	# we use zstd on default compression level (which is level 3)
	mount -o remount,compress=zstd "$data_partition_device" "$mount_point"

	# mount snapshots
	mounted_snapshots=$(grep " /snapshots " /proc/mounts)
	if [ "$mounted_snapshots" ]
	then
		echo "snapshots subvolume already mounted"
	else
		echo "mounting snapshots subvolume"
		destination="/snapshots/"
		mkdir -p "$destination"
		mount -o subvol=snapshots "$data_partition_device" "$destination"
	fi
fi

# clean up orphaned subvolume
# (created from the root subvolume when booting into a snapshot)
orphaned_id=$(btrfs subvolume list "$mount_point" | grep orphaned$ | awk '{ print $2 }')
if [ "$orphaned_id" ]
then
	echo "found orphaned subvolume with ID $orphaned_id, deleting it."
	btrfs subvolume delete --subvolid "$orphaned_id" "$mount_point"
else
	echo "no orphaned subvolume found"
fi
