#!/bin/bash

# The default configuration of swapspace (creating swapfiles in
# /var/lib/swapspace) is not usable on a Debian Live system.
#
# When a persistency partition is used, /var/lib/swapspace is accessed via the
# overlay filesystem. Unfortunately, trying to enable swapfiles residing on an
# overlay filesystem fails with the following error message:
# swapon: /var/lib/swapspace/1: swapon failed: Invalid argument
#
# When no persistency partition is used, /var/lib/swapspace is located in a
# tmpfs. Creating swapfiles there and allocating even more memory defeats the
# whole purpose of swapfiles.
#
# We don't want to mount and write swapfiles to random partitions. Therefore we
# only have two options:
# 1) When read-write persistency is enabled, it depends on its file system:
#	- btrfs: use the /swap subvolume
#	- ext4: use the persistency partition directly
# 2) Otherwise disable swapspace.

# find mounted persistence partition
eval "$(awk '$2 ~ "^/run/live/persistence/" { print "data_partition_device="$1"; mount_point="$2"; filesystem="$3"; mount_options="$4"" }' /proc/mounts)"

if [ -z "$data_partition_device" ]
then
	echo "no mounted data partition found, not starting swapspace"
	rm -f /run/swapspace_enabled
else
	echo "filesystem: \"$filesystem\""
	if [ "$filesystem" = "btrfs" ]
	then
		swapspace_path="/swap/"
	else
		swapspace_path="$mount_point"
	fi

	echo "swapspace path: $swapspace_path"
	TMP_FILE=$(mktemp -p "$swapspace_path")
	if [ -z "$TMP_FILE" ]
	then
		echo "could not write to $swapspace_path, not starting swapspace"
		rm -f /run/swapspace_enabled
	else
		rm -f "$TMP_FILE"
		echo "writable persistence path found, configuring and starting swapspace"
		sed -i "s|#swappath=.*|swappath=\"$swapspace_path\"|" /etc/swapspace.conf
		sed -i "s|swappath=.*|swappath=\"$swapspace_path\"|" /etc/swapspace.conf
		touch /run/swapspace_enabled
	fi
fi
