#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

#set -e

DEBCONF_DIR="/tmp/lernstick-config/"
if [ -d ${DEBCONF_DIR} ]
then
	mkdir -p "${DEBCONF_DIR}"
fi

DEBCONF_FILE=${DEBCONF_DIR}/lernstick-keyboard-configuration

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in $(cat /proc/cmdline)
	do
		case "${_PARAMETER}" in
			live-config.keyboard-layouts=*|keyboard-layouts=*)
				LIVE_KEYBOARD_LAYOUTS="${_PARAMETER#*keyboard-layouts=}"
				;;

			live-config.keyboard-model=*|keyboard-model=*)
				LIVE_KEYBOARD_MODEL="${_PARAMETER#*keyboard-model=}"
				;;

			live-config.keyboard-options=*|keyboard-options=*)
				LIVE_KEYBOARD_OPTIONS="${_PARAMETER#*keyboard-options=}"
				;;

			live-config.keyboard-variants=*|keyboard-variants=*)
				LIVE_KEYBOARD_VARIANTS="${_PARAMETER#*keyboard-variants=}"
				;;
		esac
	done
}

Init ()
{
	if [ -z "${LIVE_KEYBOARD_MODEL}" -a -x /usr/sbin/dmidecode ]
	then
		if /usr/sbin/dmidecode -s chassis-manufacturer | grep -q "Apple"
		then
			LIVE_KEYBOARD_MODEL="macintosh"
		else
			LIVE_KEYBOARD_MODEL="pc105"
		fi
	fi

	# enforce "lazy change" (only run the remaining script if the keyboard setting was really changed)
	KEYBOARD_STATE_FILE="/var/lib/live/config/keyboard-fixup"
	if [ ! -r ${KEYBOARD_STATE_FILE} ] || [ "${LIVE_KEYBOARD_LAYOUTS} ${LIVE_KEYBOARD_MODEL}" != "$(cat ${KEYBOARD_STATE_FILE})" ]
	then
		echo "${LIVE_KEYBOARD_LAYOUTS} ${LIVE_KEYBOARD_MODEL}" > $KEYBOARD_STATE_FILE
		Config
	fi
}

Config ()
{
	if [ -n "${LIVE_KEYBOARD_LAYOUTS}" ]
	then
		echo "keyboard-configuration keyboard-configuration/layoutcode select ${LIVE_KEYBOARD_LAYOUTS}" >> ${DEBCONF_FILE}
		sed -i -e "s|^XKBLAYOUT=.*$|XKBLAYOUT=\"${LIVE_KEYBOARD_LAYOUTS}\"|" /etc/default/keyboard
	fi

	if [ -n "${LIVE_KEYBOARD_MODEL}" ]
	then
		echo "keyboard-configuration keyboard-configuration/modelcode select ${LIVE_KEYBOARD_MODEL}" >>  ${DEBCONF_FILE}
		sed -i -e "s|^XKBMODEL=.*$|XKBMODEL=\"${LIVE_KEYBOARD_MODEL}\"|" /etc/default/keyboard
	fi

	if [ -n "${LIVE_KEYBOARD_OPTIONS}" ]
	then
		echo "keyboard-configuration keyboard-configuration/optionscode string ${LIVE_KEYBOARD_OPTIONS}" >>  ${DEBCONF_FILE}
		sed -i -e "s|^XKBOPTIONS=.*$|XKBOPTIONS=\"${LIVE_KEYBOARD_OPTIONS}\"|" /etc/default/keyboard
	fi

	if [ -n "${LIVE_KEYBOARD_VARIANTS}" ]
	then
		echo "keyboard-configuration keyboard-configuration/variantcode select ${LIVE_KEYBOARD_VARIANTS}" >>  ${DEBCONF_FILE}
		sed -i -e "s|^XKBVARIANT=.*$|XKBVARIANT=\"${LIVE_KEYBOARD_VARIANTS}\"|" /etc/default/keyboard
	fi
}

Cmdline
Init
