#!/bin/sh -e
#
# Description: Desktop selection, configures x-session-manager and default display manager
#              Must run after 1140-xserver-xorg from live-config
#

for _PARAMETER in $(cat /proc/cmdline)
do
	case "${_PARAMETER}" in
		desktop=*)
			LERNSTICK_DESKTOP="${_PARAMETER#*desktop=}"
			;;
	esac
done

echo "selected desktop: \"${LERNSTICK_DESKTOP}\""

case "${LERNSTICK_DESKTOP}" in
	kde)
		_SESSION_MANAGER="/usr/bin/startkde"
		_DISPLAY_MANAGER="/usr/bin/sddm"
		_SERVICE_NAME="sddm"
		sed -i 's/Session=.*/Session=plasma.desktop/' /etc/sddm.conf
		;;

	gnome)
		_SESSION_MANAGER="/usr/bin/gnome-session"
		_DISPLAY_MANAGER="/usr/sbin/gdm3"
		_SERVICE_NAME="gdm3"
		;;

	cinnamon)
		_SESSION_MANAGER="/usr/bin/cinnamon-session"
		_DISPLAY_MANAGER="/usr/sbin/gdm3"
		_SERVICE_NAME="gdm3"
		;;

	mate)
		_SESSION_MANAGER="/usr/bin/mate-session"
		_DISPLAY_MANAGER="/usr/sbin/gdm3"
		_SERVICE_NAME="gdm3"
		;;

	xfce)
		_SESSION_MANAGER="/usr/bin/xfce4-session"
		_DISPLAY_MANAGER="/usr/sbin/gdm3"
		_SERVICE_NAME="gdm3"
		;;

	lxde)
		_SESSION_MANAGER="/usr/bin/lxsession"
		_DISPLAY_MANAGER="/usr/sbin/gdm3"
		_SERVICE_NAME="gdm3"
		;;

	enlightenment)
		# there is no alternatives option for enlightenment...
		_DISPLAY_MANAGER="/usr/bin/sddm"
		_SERVICE_NAME="sddm"
		sed -i 's/Session=.*/Session=enlightenment.desktop/' /etc/sddm.conf
		;;

	no)
		_DISPLAY_MANAGER=""
		;;
esac

PREVIOUS_SESSION_MANAGER="$(update-alternatives --query x-session-manager | grep ^Value: | cut -f 2 -d ' ')"
echo "previous session manager: $PREVIOUS_SESSION_MANAGER"
echo "new session manager: $_SESSION_MANAGER"

if [ -n "${_SESSION_MANAGER}" -a "$PREVIOUS_SESSION_MANAGER" != "${_SESSION_MANAGER}" ]
then
	update-alternatives --set x-session-manager "${_SESSION_MANAGER}"
	rm -f /var/lib/AccountsService/users/user
fi

if ! grep -q "^${_DISPLAY_MANAGER}$" /etc/X11/default-display-manager
then
	# The user changed the default display manager, update its file and systemd symlink.
	echo "${_DISPLAY_MANAGER}" > /etc/X11/default-display-manager
	if [ -z "${_SERVICE_NAME}" ]
	then
		rm -f /etc/systemd/system/display-manager.service
		systemctl daemon-reload
	else
		ln -sf /lib/systemd/system/${_SERVICE_NAME}.service /etc/systemd/system/display-manager.service
		# As this does not start services which should be running but aren't, we have to start the display manager as well.
		# But don't wait for it to start as this would create a deadlock with live-config.
		systemctl daemon-reload
		systemctl --no-block start display-manager.service
	fi
fi
