#!/bin/sh

# We can't call debconf-set-selections in the single scripts executed by systemd
# because debconf-set-selections uses locks to prevent parallel access but
# doesn't wait for a free lock when called and just exits with the following
# error message instead:
# debconf: DbDriver "config": /var/cache/debconf/config.dat is locked by another process: Resource temporarily unavailable
#
# Therefore we let all other scripts just write their debconf values into
# single files. This script is the only place where we actually feed these
# values sequentially into debconf-set-selections.

DEBCONF_DIR="/tmp/lernstick-config/"

if [ -d ${DEBCONF_DIR} ]
then
	find ${DEBCONF_DIR} -type f -exec sh -c 'retrying-debconf-set-selections {}' \;
fi
