#!/bin/sh -e
#
# Description: Desktop selection, configures x-session-manager and default display manager
#              Must run after 1140-xserver-xorg from live-config
#

for _PARAMETER in $(cat /proc/cmdline)
do
	case "${_PARAMETER}" in
		desktop=*)
			LERNSTICK_DESKTOP="${_PARAMETER#*desktop=}"
			;;
	esac
done

echo "selected desktop: \"${LERNSTICK_DESKTOP}\""

# support for "lazy" configuration changes
DESKTOP_STATE_FILE="/var/lib/live/config/lernstick-desktop"
if [ -r ${DESKTOP_STATE_FILE} ] && [ "${LERNSTICK_DESKTOP}" = "$(cat ${DESKTOP_STATE_FILE})" ]
then
	echo "desktop \"${LERNSTICK_DESKTOP}\" already set, nothing to do"
	exit 0
fi

# the values in _XSESSION have to match the file names in
# /usr/share/xsessions/*.desktop
_DISPLAY_MANAGER="/usr/sbin/gdm3"
_DISPLAY_MANAGER_SERVICE_FILENAME="gdm3"
case "${LERNSTICK_DESKTOP}" in
	kde)
		_DISPLAY_MANAGER="/usr/bin/sddm"
		_DISPLAY_MANAGER_SERVICE_FILENAME="sddm"
		_SESSION_MANAGER="/usr/bin/startplasma-x11"
		_XSESSION="plasma"
		sed -i 's|Session=.*|Session=/usr/share/xsessions/plasmax11.desktop|' /etc/sddm.conf
		;;

	gnome)
		_SESSION_MANAGER="/usr/bin/gnome-session"
		_XSESSION="gnome-xorg"
		;;

	gnome-wayland)
		_SESSION_MANAGER="/usr/bin/gnome-session"
		_XSESSION="gnome"
		;;

	cinnamon)
		_SESSION_MANAGER="/usr/bin/cinnamon-session"
		_XSESSION="cinnamon"
		;;

	mate)
		_SESSION_MANAGER="/usr/bin/mate-session"
		_XSESSION="mate"
		;;

	xfce)
		_SESSION_MANAGER="/usr/bin/startxfce4"
		_XSESSION="xfce"
		;;

	lxde)
		_SESSION_MANAGER="/usr/bin/lxsession"
		_XSESSION="LXDE"
		;;

	enlightenment)
		# there is no session manager alternatives for enlightenment...
		_XSESSION="enlightenment"
		;;

	no)
		_DISPLAY_MANAGER=""
		_DISPLAY_MANAGER_SERVICE_FILENAME=""
		;;
esac

if [ -n "${_SESSION_MANAGER}" ]
then
	update-alternatives --set x-session-manager "${_SESSION_MANAGER}"
fi

if [ -n "${_XSESSION}" ]
then
	_AS_CONFIG_FILE="/var/lib/AccountsService/users/user"
	if [ ! -f ${_AS_CONFIG_FILE} ]
	then
cat << EOF > ${_AS_CONFIG_FILE}
[User]
Language=
XSession=
SystemAccount=false
EOF
	fi
	sed -i "s/XSession=.*/XSession=${_XSESSION}/g" ${_AS_CONFIG_FILE}
fi

if ! grep -q "^${_DISPLAY_MANAGER}$" /etc/X11/default-display-manager
then
	echo "${_DISPLAY_MANAGER}" > /etc/X11/default-display-manager

	if [ -z "${_DISPLAY_MANAGER_SERVICE_FILENAME}" ]
	then
		echo "removing /etc/systemd/system/display-manager.service"
		rm -f /etc/systemd/system/display-manager.service
		_TARGET="multi-user.target"
	else
		echo "linking /lib/systemd/system/${_DISPLAY_MANAGER_SERVICE_FILENAME}.service to /etc/systemd/system/display-manager.service"
		ln -sf /lib/systemd/system/${_DISPLAY_MANAGER_SERVICE_FILENAME}.service /etc/systemd/system/display-manager.service
		_TARGET="graphical.target"
	fi
	systemctl set-default ${_TARGET}
	systemctl daemon-reload
	systemctl --no-block isolate ${_TARGET}
fi

echo "${LERNSTICK_DESKTOP}" > ${DESKTOP_STATE_FILE}
