#!/bin/bash
# (this must be bash instead of plain sh because we need hash tables)

declare -A mac_layouts
mac_layouts[ch(de_nodeadkeys)]="mac_special(ch_nodeadkeys)"
mac_layouts[ch(fr)]="mac_special(ch_fr)"
mac_layouts[ch]="mac_special(ch)"
mac_layouts[de]="mac_special(de)"
mac_layouts[fr]="mac_special(fr)"
mac_layouts[us]="mac_special(us)"

# Here we configure all the stuff that has to be configured on every boot.

LIVE_USERNAME="user"

# Reading configuration files from filesystem and live-media
for _FILE in /etc/live/config.conf \
             /etc/live/config.conf.d/* \
             /lib/live/mount/medium/live/config.conf \
             /lib/live/mount/medium/live/config/*
do
	if [ -e "${_FILE}" ]
	then
		. "${_FILE}"
	fi
done

# Reading kernel command line
for _PARAMETER in $(cat /proc/cmdline)
do
	case "${_PARAMETER}" in
		live-config.keyboard-layouts=*|keyboard-layouts=*)
			LIVE_KEYBOARD_LAYOUTS="${_PARAMETER#*keyboard-layouts=}"
			;;

		live-config.username=*|username=*)
			LIVE_USERNAME="${_PARAMETER#*username=}"
			;;
	esac
done

update_keyboard_selectors()
{

	# We had many complaints from Mac users that the keyboard shortcuts they are used to no longer work in Linux.
	# Therefore we try here to give Mac users more familiar keyboard settings:
	if [ "${LIVE_KEYBOARD_MODEL}" = "macintosh" ]
	then
		MAC_KEYBOARD_LAYOUTS=""
		for i in $(echo ${LIVE_KEYBOARD_LAYOUTS} | sed "s/,/ /g")
		do
			MAPPED_LAYOUT="${mac_layouts[$i]}"
			echo "mapping $i to special mac layout ${MAPPED_LAYOUT}"
			if [ -n "${MAC_KEYBOARD_LAYOUTS}" ]
			then
				MAC_KEYBOARD_LAYOUTS="${MAC_KEYBOARD_LAYOUTS},"
			fi
			if [ -n "${MAPPED_LAYOUT}" ]
			then
				MAC_KEYBOARD_LAYOUTS="${MAC_KEYBOARD_LAYOUTS}${MAPPED_LAYOUT}"
			else
				MAC_KEYBOARD_LAYOUTS="${MAC_KEYBOARD_LAYOUTS}$i"
			fi
		done
		echo "mapped keyboard layouts: ${MAC_KEYBOARD_LAYOUTS}"
		LIVE_KEYBOARD_LAYOUTS="${MAC_KEYBOARD_LAYOUTS}"
	fi

	# configure KDE
	cat > "/home/${LIVE_USERNAME}/.kde/share/config/kxkbrc" << EOF
[Layout]
DisplayNames=${LIVE_KEYBOARD_LAYOUTS}
IndicatorOnly=false
LayoutList=${LIVE_KEYBOARD_LAYOUTS}
ShowFlag=false
SwitchMode=Global
Use=true
EOF
	chown ${LIVE_USERNAME}:${LIVE_USERNAME} "/home/${LIVE_USERNAME}/.kde/share/config/kxkbrc"
	if [ -w  "/home/${LIVE_USERNAME}/.kde/share/apps/kded/session/keyboard/layout_memory.xml" ]
	then
		# set first layout in list as currently selected layout
		FIRST_LAYOUT="$(echo "${LIVE_KEYBOARD_LAYOUTS}" | awk -F , '{ print $1 }')"
		sed -i "s/currentLayout=\".*\"/currentLayout=\"${FIRST_LAYOUT}\"/1" \
			"/home/${LIVE_USERNAME}/.kde/share/apps/kded/session/keyboard/layout_memory.xml"
	fi

	# configure gsettings based desktops (GNOME, Cinnamon & MATE)
	if [ -e /usr/bin/gsettings ]
	then
		GNOME_INPUT_SOURCES=""
		GNOME_KEYBOARD_LAYOUTS=""
		IFS=" "
		for i in $(echo "$LIVE_KEYBOARD_LAYOUTS" | sed "s/,/ /g")
		do
		        # GNOME has its own standard of keyboard layout definitions (parentheses are removed and a "+" separator is added instead).
			# Cinnamon and MATE (based on GNOME!) use
			# - each a different gsettings key
			# - even another standard for keyboard layout definitions (parentheses are removed and a tab separator is added instead).
	                GNOME_INPUT_SOURCE="$(echo "$i" | sed "s/(/+/g" | sed "s/)//g")"
			GNOME_KEYBOARD_LAYOUT="$(echo "$i" | sed "s/(/\t/g" | sed "s/)//g")"

		        if [ -n "${GNOME_INPUT_SOURCES}" ]
		        then
		                GNOME_INPUT_SOURCES="${GNOME_INPUT_SOURCES}, "
		        fi
		        GNOME_INPUT_SOURCES="${GNOME_INPUT_SOURCES}('xkb', '${GNOME_INPUT_SOURCE}')"

			if [ -n "${GNOME_KEYBOARD_LAYOUTS}" ]
		        then
		                GNOME_KEYBOARD_LAYOUTS="${GNOME_KEYBOARD_LAYOUTS}, "
		        fi
		        GNOME_KEYBOARD_LAYOUTS="${GNOME_KEYBOARD_LAYOUTS}'${GNOME_KEYBOARD_LAYOUT}'"
		done
		echo "GNOME_INPUT_SOURCES:\"${GNOME_INPUT_SOURCES}\""
		echo "GNOME_KEYBOARD_LAYOUTS:\"${GNOME_KEYBOARD_LAYOUTS}\""

		# For some unknown reason we first have to delete the settings and
		# sleep for a second. Only then the settings are successfully applied.
		# (order: GNOME, Cinnamon, MATE)
		sudo -u "${LIVE_USERNAME}" dbus-run-session gsettings set org.gnome.desktop.input-sources sources "[]"
		sudo -u "${LIVE_USERNAME}" dbus-run-session gsettings set org.gnome.libgnomekbd.keyboard layouts "[]"
		sudo -u "${LIVE_USERNAME}" dbus-run-session gsettings set org.mate.peripherals-keyboard-xkb.kbd layouts "[]"
		sleep 1
		sudo -u "${LIVE_USERNAME}" dbus-run-session gsettings set org.gnome.desktop.input-sources sources "[${GNOME_INPUT_SOURCES}]"
		sudo -u "${LIVE_USERNAME}" dbus-run-session gsettings set org.gnome.libgnomekbd.keyboard layouts "[${GNOME_KEYBOARD_LAYOUTS}]"
		sudo -u "${LIVE_USERNAME}" dbus-run-session gsettings set org.mate.peripherals-keyboard-xkb.kbd layouts "[${GNOME_KEYBOARD_LAYOUTS}]"
	fi
}

# enforce "lazy change" (only update the keyboard selectors if the keyboard setting was really changed)
if [ -z "${LIVE_KEYBOARD_MODEL}" -a -x /usr/sbin/dmidecode ]
then
	if /usr/sbin/dmidecode -s chassis-manufacturer | grep -q "Apple"
	then
		LIVE_KEYBOARD_MODEL="macintosh"
	else
		LIVE_KEYBOARD_MODEL="pc105"
	fi
fi
KEYBOARD_STATE_FILE="/var/lib/live/config/user-setup-keyboard-selectors"
OLD_CONFIG="$(cat ${KEYBOARD_STATE_FILE})"
if [ -r ${KEYBOARD_STATE_FILE} ] && [ "${LIVE_KEYBOARD_LAYOUTS} ${LIVE_KEYBOARD_MODEL}" = "${OLD_CONFIG}" ]
then
	echo "keyboard config (\"${LIVE_KEYBOARD_LAYOUTS} ${LIVE_KEYBOARD_MODEL}\") unchanged, skipping update"
else
	echo "keyboard config changed from \"${OLD_CONFIG}\" to \"${LIVE_KEYBOARD_LAYOUTS} ${LIVE_KEYBOARD_MODEL}\", updating"
	echo "${LIVE_KEYBOARD_LAYOUTS} ${LIVE_KEYBOARD_MODEL}" > $KEYBOARD_STATE_FILE
	update_keyboard_selectors
fi

XFCE4_PANEL_DEFAULTS="/etc/xdg/xfce4/panel/default.xml"
if [ -e "${XFCE4_PANEL_DEFAULTS}" ]
then
	# When the configuration is not there yet, XFCE asks the user if (s)he wants to start with the default or an empty panel.
	# But who on earth wants to start with an *empty* panel?!
	# Therefore we put the default panel there if not yet existing.
	PANEL_DIR="/home/${LIVE_USERNAME}/.config/xfce4/xfconf/xfce-perchannel-xml"
	PANEL_FILE="${PANEL_DIR}/xfce4-panel.xml"
	if [ ! -e "${PANEL_FILE}" ]
	then
		sudo -u "${LIVE_USERNAME}" mkdir -p "${PANEL_DIR}"
		sudo -u "${LIVE_USERNAME}" cp "${XFCE4_PANEL_DEFAULTS}" "${PANEL_FILE}"
	fi
fi
