#!/bin/sh

# Workaround for bug in shadow
set +e
/usr/lib/user-setup/user-setup-apply 2>&1 \
| grep -v "Shadow passwords are now on"
set -e

# Creating state file
touch /var/lib/live/config/user-setup
