#!/bin/bash

# NetworkManager connections are per default restricted to the MAC address used
# at setup time. This is not what we want on a live system. We want to use the
# configured network connections on any hardware we are booting on. Therefore we
# remove the mac-address lines from the system connections config files.

sed -i '/mac-address=.*/d' /etc/NetworkManager/system-connections/*
