#!/bin/sh -e
#
# Description: Desktop selection, configures x-session-manager and default display manager
#              Must run after 1140-xserver-xorg from live-config
#

echo -n " lernstick-desktop"

LOGFILE=/var/log/lernstick-desktop

for _PARAMETER in $(cat /proc/cmdline)
do
	case "${_PARAMETER}" in
		desktop=*)
			LERNSTICK_DESKTOP="${_PARAMETER#*desktop=}"
			;;
	esac
done

echo "LERNSTICK_DESKTOP: \"${LERNSTICK_DESKTOP}\"" > ${LOGFILE}

# sometimes users end up with an empty .dmrc file
# this heavily confuses kdm (it starts just gnome-terminal) and makes users mad
# therefore we always remove this file here
rm -f /home/user/.dmrc

case "${LERNSTICK_DESKTOP}" in
        kde)
                _SESSION_MANAGER="/usr/bin/startkde"
                _DISPLAY_MANAGER="/usr/bin/sddm"
                _SERVICE_NAME="sddm"
                ;;

        gnome)
                _SESSION_MANAGER="/usr/bin/gnome-session"
                _DISPLAY_MANAGER="/usr/sbin/gdm3"
                _SERVICE_NAME="gdm3"
                ;;

        cinnamon)
                _SESSION_MANAGER="/usr/bin/cinnamon-session"
                _DISPLAY_MANAGER="/usr/sbin/gdm3"
                _SERVICE_NAME="gdm3"
                ;;

        mate)
                _SESSION_MANAGER="/usr/bin/mate-session"
                _DISPLAY_MANAGER="/usr/sbin/gdm3"
                _SERVICE_NAME="gdm3"
                ;;

        xfce)
                _SESSION_MANAGER="/usr/bin/xfce4-session"
                _DISPLAY_MANAGER="/usr/sbin/gdm3"
                _SERVICE_NAME="gdm3"
                ;;

        lxde)
                _SESSION_MANAGER="/usr/bin/lxsession"
                _DISPLAY_MANAGER="/usr/sbin/gdm3"
                _SERVICE_NAME="gdm3"
                ;;

        enlightenment)
                cat > /home/user/.dmrc << EOF
[Desktop]
Session=enlightenment
EOF
                _DISPLAY_MANAGER="/usr/sbin/gdm3"
                _SERVICE_NAME="gdm3"
                ;;

        no)
                _DISPLAY_MANAGER=""
                ;;
esac

if [ -n "${_SESSION_MANAGER}" -a "$(update-alternatives --query x-session-manager | grep ^Value: | cut -f 2 -d '')" != "${_SESSION_MANAGER}" ]
then
        update-alternatives --set x-session-manager "${_SESSION_MANAGER}" >> ${LOGFILE} 2>&1
fi

if ! grep -q "^${_DISPLAY_MANAGER}$" /etc/X11/default-display-manager
then
	# The user changed the default display manager, update its file and systemd symlink.
        echo "${_DISPLAY_MANAGER}" > /etc/X11/default-display-manager
	if [ -z "${_SERVICE_NAME}" ]
	then
		rm -f /etc/systemd/system/display-manager.service
	        systemctl daemon-reload
	else
		ln -sf /lib/systemd/system/${_SERVICE_NAME}.service /etc/systemd/system/display-manager.service
		# As this does not start services which should be running but aren't, we have to start the display manager as well.
	        # But don't wait for it to start as this would create a deadlock with live-config.
	        systemctl daemon-reload
	        systemctl --no-block start display-manager.service
	fi
fi

echo "done." >> ${LOGFILE}

