#!/bin/sh
set -e

if [ "$1" = "prereqs" ]; then exit 0; fi

. /usr/share/initramfs-tools/hook-functions

BLACKLIST=/etc/modprobe.d/lernstick-blacklists-nouveau.conf

if [ -f "$BLACKLIST" ]; then
	rm -f "$DESTDIR$BLACKLIST"
	copy_file config "$BLACKLIST"
fi
